<x-app-layout>
    <x-slot name="seo_title">
        {{$page->seo_title}}
    </x-slot>
    <x-slot name="seo_description">
        {{$page->seo_description}}
    </x-slot>
    <x-slot name="seo_keywords">
        {{$page->seo_keywords}}
    </x-slot>

    <div class="container">
        <div class="container-inner container-block promo-box">
            <div class="boxes">
                <div class="box-md-5 box-xl-6">
                    <h2>How does the <u>BTC&nbsp;Mixer</u> work?</h2>
                </div>
                <div class="box-md-5 box-xl-4">
                    <p><strong>BTC mixer is a tool that makes BTC (more) anonymous. </strong>It works pretty
                        straightforwardly. The sender of the payment puts their money into a pool, which then
                        "shuffles" around all the Bitcoins and divides them into the recipients&rsquo; addresses
                        based on the amount sent.</p>
                    <p class="md-center">
                        <img src="/assets/web/images/content-1.png" alt="How does the BTC&nbsp;Mixer work?"
                             title="How does the BTC&nbsp;Mixer work?">
                    </p>

                    <p>Here's how Whir works in three easy steps:</p>
                    <p>1) <strong>Enter the BTC address (or addresses) where you want to receive the mixed
                            Bitcoins.</strong> Optionally, set the delay to process your transaction. The longer the
                        delay, the higher the anonymity of the mixed Bitcoins.</p>
                    <p>2) <strong>Send the Bitcoins you want to mix</strong> to the address generated by Whir.</p>
                    <p>3) <strong>After the first confirmation of your deposit, Whir will mix your Bitcoins</strong>
                        and send them to the address (or addresses) entered in the first step.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-inner container-block promo-box bg-light lg-radius">
            <div class="boxes">
                <div class="box-sm-3">
                    <div class="sm-start center">
                        <img src="/assets/web/images/content-2-xs.png" width="280px" class="pixelated box-img"
                             alt="Isn’t bitcoin anonymous" title="Isn’t bitcoin anonymous">
                    </div>
                </div>

                <div class="box-sm-7">
                    <h2>But wait... isn’t bitcoin <u>anonymous</u>?</h2>
                    <div class="boxes">
                        <div class="box-sm-5">
                            <div class="pe-md-4">
                                <p>Absolutely not &mdash; BTC is pseudo-anonymous. <strong>Sending and receiving
                                        BTC leaves a fingerprint. </strong>If the fingerprint is ever linked to
                                    your
                                    identity, everything you have ever "touched" will be linked to you.</p></div>
                        </div>

                        <div class="box-sm-5">
                            <div class="pe-md-4">
                                <p>All the &ldquo;fingerprints&rdquo; are publicly stored in BTC&rsquo;s
                                    blockchain. Therefore, <strong>anyone you send BTC to can look up your
                                        previous transactions or even see your crypto balance.</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-inner container-block promo-box">
            <h2 class="center">
                How can a mixer make<br class="md-show"/> BTC anonymous?<br class="md-show"/> <u>CoinJoin</u> is
                the answer. </h2>

            <div class="boxes">
                <div class="box-md-2"></div>
                <div class="box-md-6">
                    <p><strong>CoinJoin is a type of anonymous transaction that helps BTC users maintain their
                            privacy while sending BTC.</strong> CoinJoin is a multiparty "BTC mixing"
                        transaction at the end of which it is unclear who owns which coin.</p>
                    <p>Consider the following transactions made at the same time: A purchases an item from B, C
                        purchases an item from D, and E purchases an item from F. Without CoinJoin, the public
                        blockchain ledger would record three separate transactions for each input-output match.</p>
                    <p>With CoinJoin, only one single transaction is recorded. The ledger would show that Bitcoins
                        were paid from A, C, and E addresses to B, D, and F. By masking the deals made by all
                        parties, an observer cannot with full certainty determine who sent Bitcoins to whom.</p>
                    <p>While some believe that CoinJoin is a new technology, this is not valid. CoinJoin is simply
                        an advancement on already existing technology &ndash; BTC. And BTC mixers bring
                        CoinJoin technology to users.</p>
                </div>
                <div class="box-md-2"></div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-inner container-block promo-box bg-light lg-radius">
            <div class="boxes">
                <div class="box-sm-3">
                    <div class="sm-start center">
                        <img src="/assets/web/images/content-3-xs.png" width="300px" class="pixelated box-img"
                             alt="Is it safe to use a BTC mixer?" title="Is it safe to use a BTC mixer?">
                    </div>
                </div>

                <div class="box-sm-7">
                    <h2>
                        <u>Is it safe</u> to use <br class="md-show"/>a BTC mixer? </h2>

                    <div class="boxes">
                        <div class="box-sm-5">
                            <div class="pe-md-4">
                                <p>It is absolutely safe to use Whir. However, as with almost everything else
                                    related to crypto, it is entirely up to you to decide whether it is necessary to
                                    use a BTC mixer.</p></div>
                        </div>

                        <div class="box-sm-5">
                            <div class="pe-md-4">
                                <p>Before using our Bitcon mixer, do a due diligence and read our <a
                                        href="{{url('/terms')}}">Terms</a>.<strong> However, we always suggest to
                                        mix
                                        smaller amounts instead of large chunks of coins at once.</strong></p></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-inner container-block promo-box">
            <h2 class="center">
                Why should I choose<br class="md-show"/> Whir BTC Mixer? </h2>

            <div class="boxes">
                <div class="box-md-2-5"></div>

                <div class="box-md-5">
                    <h3>FAST BITCOIN MIXER</h3>
                    <p>The speed of a BTC mixer can be an important consideration for users who want to quickly
                        and efficiently obscure the origin of their Bitcoin transactions.</p>
                    <p><strong>Whir Bitcoin mixer offers an instant mixing service, which allows you to receive your
                            mixed Bitcoin within a few minutes after the first confirmation of your
                            deposit. </strong>
                    </p>
                    <p>Optionally, to enhance the privacy of the Bitcoin mixing transaction, you can choose a delay
                        in processing your mixing request.</p>
                    <h3>SECURE BITCOIN MIXER</h3>
                    <p>The security of a Bitcoin mixer can vary depending on the specific service being used. Some
                        Bitcoin mixers may have strong security measures in place to protect the privacy of their
                        users, while others may be less secure.</p>
                    <p>It is important to carefully research any Bitcoin mixer that you are considering using and to
                        ensure that they have strong security measures in place. This can include things like secure
                        servers, encrypted communication, and anonymous registration processes.</p>
                    <p>To guarantee the highest level of server and application security at all times, Whir employs
                        a team of IT and security specialists. <strong>Additionally, to increase the safety and
                            privacy of our users, we never require or log any personal details, such as name, email,
                            or IP address, and delete all transaction details after 24 hours. </strong></p>
                    <h3>CONVENIENT BITCOIN MIXER</h3>
                    <p>The convenience of a Bitcoin mixer can depend on a few factors, such as the user's specific
                        needs and the features and user experience of the mixer service being used.</p>
                    <p>Some users may find Bitcoin mixers to be convenient because they allow them to quickly and
                        easily obscure the origin of their Bitcoin transactions. Other users may find Bitcoin mixers
                        to be inconvenient because they may have limits on the amount of Bitcoin that can be mixed
                        at one time, or because they may require users to go through additional steps to use the
                        service.</p>
                    <p><strong>Whir Bitcoin mixer combines the speed, privacy and affordability, while allowing you
                            to mix up to 10 BTC in a single transaction, without registration or KYC.</strong></p>
                </div>

                <div class="box-md-2-5"></div>
            </div>
        </div>
    </div>

    <div class="container container-md">
        <div class="container-inner container-block promo-box bg-light md-radius">
            <h2 class="center">Bitcoin mixer FAQ</h2>
            <div class="accordion" id="faq">
                <div class="accordion-item">
                    <h3 class="accordion-header" id="tab-head-0">
                        What is Whir? </h3>
                    <div id="tab-0" class="accordion-collapse" aria-labelledby="tab-head-0">
                        <p>Whir is a service that returns privacy to your Bitcoin by utilizing a Bitcoin mixnig
                            method called CoinJoin. </p></div>
                </div>
                <div class="accordion-item">
                    <h3 class="accordion-header" id="tab-head-1">
                        What is a Bitcoin mixer? </h3>
                    <div id="tab-1" class="accordion-collapse" aria-labelledby="tab-head-0">
                        <p><strong>A Bitcoin mixer, also known as a Bitcoin tumbler, is a service that is used to
                                obscure the origin of Bitcoin transactions.</strong> When a Bitcoin transaction is
                            made,
                            it is recorded on the blockchain, which is a public record of all Bitcoin transactions.
                            The blockchain allows anyone to see the transaction history of any Bitcoin address. This
                            can be a problem for people who want to keep their Bitcoin transactions private, as
                            anyone can see how much money they have sent and received.</p>
                        <p>A Bitcoin mixer works by taking in Bitcoin from many different people and then sending
                            out new Bitcoin to different addresses, making it difficult to trace the original
                            transactions. <strong>This can be useful for people who want to keep their Bitcoin
                                transactions private for various reasons, such as for privacy or to protect
                                themselves from being targeted by hackers.</strong></p>
                    </div>
                </div>
                <div class="accordion-item">
                    <h3 class="accordion-header" id="tab-head-2">
                        Why should I use a Bitcoin mixer? </h3>
                    <div id="tab-2" class="accordion-collapse" aria-labelledby="tab-head-0">
                        <p>There are a few reasons why someone might want to use a Bitcoin mixer:</p>
                        <p><strong>Privacy. </strong>Using a Bitcoin mixer can help to obscure the origin of a
                            person's Bitcoin transactions, which can provide an additional layer of privacy.</p>
                        <p><strong>Security. </strong>If someone's Bitcoin address is publicly known, they may be
                            more vulnerable to hacking attacks. By using a Bitcoin mixer to obscure the origin of
                            their transactions, they can make it more difficult for hackers to target them.</p>
                        <p><strong>Anonymity. </strong>Some people may want to use Bitcoin anonymously, either for
                            personal privacy or to protect themselves from potential repercussions in countries
                            where Bitcoin is not legal. A Bitcoin mixer can help to obscure the identity of the
                            person making the transaction.</p>
                    </div>
                </div>
                <div class="accordion-item">
                    <h3 class="accordion-header" id="tab-head-3">
                        Isn't Bitcoin anonymous? </h3>
                    <div id="tab-3" class="accordion-collapse" aria-labelledby="tab-head-0">
                        <p><strong>Bitcoin is often referred to as an anonymous digital currency, but in reality, it
                                is only pseudonymous. </strong>While Bitcoin transactions do not contain any
                            personal
                            information about the people involved, they are still recorded on the blockchain, which
                            is a public ledger. This means that anyone can see the transaction history of any
                            Bitcoin address.</p>
                        <p>Therefore, while Bitcoin transactions are not directly linked to a person's real-world
                            identity, they can still be traced through other means. For example, if someone uses
                            their real identity to buy Bitcoin or if they use their Bitcoin address for other
                            purposes (such as posting it online or associating it with their online identity), then
                            it may be possible to trace their Bitcoin transactions back to them.</p>
                        <p><strong>For this reason, some people choose to use a Bitcoin mixer to obscure the origin
                                of their transactions and provide an additional layer of anonymity. </strong></p>
                    </div>
                </div>
                <div class="accordion-item">
                    <h3 class="accordion-header" id="tab-head-4">
                        Is Whir anonymous? </h3>
                    <div id="tab-4" class="accordion-collapse" aria-labelledby="tab-head-0">
                        <p><strong>Absolutely. Whir is an anonymous, non-KYC Bitcoin mixing service. </strong></p>
                        <p>We never ask for user names, email addresses, or other forms of identification.
                            Additionally, we don&rsquo;t log IP addresses and don&rsquo;t use tracking scripts.</p>
                    </div>
                </div>
                <div class="accordion-item">
                    <h3 class="accordion-header" id="tab-head-5">
                        Do you require KYC? </h3>
                    <div id="tab-5" class="accordion-collapse" aria-labelledby="tab-head-0">
                        <p>Know Your Customer (KYC) is a process that financial institutions and other regulated
                            companies use to verify the identity of their clients and assess their potential risks
                            for money laundering or financing terrorism.</p>
                        <p>The KYC process typically involves collecting and verifying personal information about a
                            customer, such as their name, address, and date of birth. This information is used to
                            identify the customer and confirm that they are who they claim to be. In some cases, a
                            company may also ask for additional information or documents, such as a
                            government-issued ID or proof of address, to complete the KYC process.</p>
                        <p>The purpose of KYC is to help companies comply with anti-money laundering (AML) and
                            counter-terrorism financing (CTF) regulations, which require them to have a thorough
                            understanding of their customers and their financial activities. By collecting and
                            verifying this information, companies can better identify and mitigate any potential
                            risks associated with their customers.</p>
                        <p>It is not necessary to do Know Your Customer (KYC) when using Bitcoin as a currency.
                            Bitcoin is a decentralized digital currency that allows users to send and receive
                            payments without the need for a central authority or financial institution. This means
                            that there is no requirement for users to provide personal information or go through a
                            KYC process when using Bitcoin.</p>
                        <p><strong>Therefore, we do not require users to complete a KYC process in order to use our
                                platform. </strong></p></div>
                </div>
                <div class="accordion-item">
                    <h3 class="accordion-header" id="tab-head-6">
                        Are there any Bitcoin mixing limits? </h3>
                    <div id="tab-6" class="accordion-collapse" aria-labelledby="tab-head-0">
                        <p>Whir Bitcoin mixer have limits on the amount of Bitcoin that can be mixed at one
                            time.</p>
                        <p>The minimum amount you can mix is {{$settings->get('min_amount_btc',0.01)}} BTC.</p>
                        <p>Even though some Bitcoin mixers promise to mix up to 1000 BTC at once,<strong> to
                                guarantee the best privacy, and legal status of the transactions, Whir limits each
                                transaction up to {{$settings->get('max_amount_btc',1)}} BTC.</strong></p></div>
                </div>
                <div class="accordion-item">
                    <h3 class="accordion-header" id="tab-head-7">
                        How long does it take to process transaction? </h3>
                    <div id="tab-7" class="accordion-collapse" aria-labelledby="tab-head-0">
                        <p><strong>As soon as we receive the third confirmation of your transaction, we will
                                initiate the Bitcoin mixing transaction.</strong></p>
                        <p>If you chose "instant mixing" service, you will receive your mixed Bitcoin within a few
                            minutes.</p>
                        <p>If you chose a delay, the mixing transaction can potentially take several hours or more
                            to complete the process.</p></div>
                </div>
                <div class="accordion-item">
                    <h3 class="accordion-header" id="tab-head-8">
                        How does a Bitcoin mixer makes Bitcoin private? </h3>
                    <div id="tab-8" class="accordion-collapse" aria-labelledby="tab-head-0">
                        <p><strong>A Bitcoin mixer works by taking in Bitcoin from many different people and then
                                sending out new Bitcoin to different addresses. </strong>This makes it difficult to
                            trace the original transactions, as the funds have been mixed with the funds of many
                            other people.</p>
                        <p>For example, imagine that Alice wants to send 1 Bitcoin to Bob. If Alice sends the
                            Bitcoin directly from her wallet to Bob's wallet, the transaction will be recorded on
                            the blockchain, which is a public ledger of all Bitcoin transactions. Anyone can see
                            that Alice sent 1 Bitcoin to Bob, and they can also see the transaction history of both
                            Alice's and Bob's Bitcoin addresses.</p>
                        <p>Now imagine that Alice uses a Bitcoin mixer to send the 1 Bitcoin to Bob. The mixer takes
                            in Bitcoin from Alice and many other people, and then sends out new Bitcoin to different
                            addresses. This makes it difficult to trace the original transactions, as the funds have
                            been mixed with the funds of many other people. Therefore, it is more difficult to see
                            that Alice sent 1 Bitcoin to Bob, as the transaction is mixed with many other
                            transactions.</p>
                        <p>This privacy-enhancing technique used to mix Bitcoin transactions is referred to as
                            CoinJoin. CoinJoin works by allowing multiple users to combine their Bitcoin
                            transactions into a single transaction, making it more difficult to determine which
                            input corresponds to which output.</p>
                        <p>With CoinJoin, the transactions can be combined into a single transaction with multiple
                            inputs and outputs. This makes it more difficult to determine which input corresponds to
                            which output.</p>
                    </div>
                </div>
                <div class="accordion-item">
                    <h3 class="accordion-header" id="tab-head-9">
                        Do you keep transaction logs? </h3>
                    <div id="tab-9" class="accordion-collapse" aria-labelledby="tab-head-0">
                        <p><strong>We permanently delete all transaction logs 24 hours after the Bitcoin mixing
                                transaction is complete. </strong></p>
                        <p>We do not log IP addresses and do not use 3rd party tracking scripts from Google or
                            Facebook.</p>
                    </div>
                </div>
            </div>
            <p class="md-start center accordion-opts">
                <a class="btn btn-dark text-nouppercase" href="{{url('/faq')}}">
                    VIEW ALL FAQs </a>
            </p>
        </div>
    </div>

    <div class="container">
        <div class="container-inner container-block promo-box">
            <h2 class="md-center">
                Everyone has right<br class="md-show"/> for their <u>privacy</u>. </h2>

            <div class="boxes">
                <div class="box-md-1-5"></div>
                <div class="box-md-7  md-center">
                    <p><a href="#" target="_blank" rel="noopener"><strong>Privacy
                                is a fundamental human right</strong></a> recognized by the UN Declaration of Human
                        rights,
                        the International Covenant on Civil and Political Rights and in other treaties. No matter
                        who you are, Whir is for all of you*, and these are our clients:</p></div>
            </div>

            <div class="md-center faces">
                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-1-xs.png" alt="Bitcoin mixer for activists"
                             title="Bitcoin mixer for activists" height="115px">
                        <figcaption>Activists</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-2-xs.png" alt="Bitcoin mixer for journalists"
                             title="Bitcoin mixer for journalists" height="115px">
                        <figcaption>Journalists</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-3-xs.png" alt="Bitcoin mixer for libertarians"
                             title="Bitcoin mixer for libertarians" height="115px">
                        <figcaption>Libertarians</figcaption>
                    </figure>
                </a>

                <a href="https://whir.to/use-cases/sugar-daddies">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-4-xs.png" alt="Bitcoin mixer for sugar daddies"
                             title="Bitcoin mixer for sugar daddies" height="115px">
                        <figcaption>Sugar daddies</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-6-xs.png" alt="Bitcoin mixer for onlyfans"
                             title="Bitcoin mixer for onlyfans" height="115px">
                        <figcaption>Onlyfans</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-5-xs.png" alt="Bitcoin mixer for adults"
                             title="Bitcoin mixer for adults" height="115px">
                        <figcaption>Adults</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-7-xs.png" alt="Bitcoin mixer for privacy extremists"
                             title="Bitcoin mixer for privacy extremists" height="115px">
                        <figcaption>Privacy extremists</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-8-xs.png" alt="Bitcoin mixer for cillionaires"
                             title="Bitcoin mixer for cillionaires" height="115px">
                        <figcaption>Cillionaires</figcaption>
                    </figure>
                </a>
            </div>

            <div class="boxes">
                <div class="box-md-1-5"></div>
                <div class="box-md-7">
                    <div class="md-center privacy-appendix">
                        <p>* Okay, let&rsquo;s be clear. Privacy is absolutely vital for the bad guys, too. We,
                            however, do not support the crooks, and our service is not suitable for them either.
                            Even though Whir does the best to anonymize the transactions, there are far better coins
                            for crypto anonymity, such as <a href="#">Monero</a> or <a
                                href="#">zcash</a>. Please read <a href="{{url('terms')}}">our&nbsp;terms</a>
                            before use.</p></div>

                    <blockquote class="autoquote with-author">
                        People should have privacy. Governments should have transparency.
                    </blockquote>

                    <p class="center author">
                        — Julian Assange </p>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
