<x-app-layout>
    <x-slot name="seo_title">
        {{$page->seo_title}}
    </x-slot>
    <x-slot name="seo_description">
        {{$page->seo_description}}
    </x-slot>
    <x-slot name="seo_keywords">
        {{$page->seo_keywords}}
    </x-slot>

    <div class="container">
        <div class="container-inner container-block promo-box">
            <div class="boxes">
                <div class="box-md-5 box-xl-6">
                    <h2>How does the <u>BTC&nbsp;Mixer</u> work?</h2>
                </div>
                <div class="box-md-5 box-xl-4">
                    <p><strong>BTC mixer is a tool that makes BTC (more) anonymous. </strong>It works pretty
                        straightforwardly. The sender of the payment puts their money into a pool, which then
                        "shuffles" around all the BTC and divides them into the recipients&rsquo; addresses
                        based on the amount sent.</p>
                    <p class="md-center">
                        <img src="/assets/web/images/content-1.png" alt="How does the BTC&nbsp;Mixer work?"
                             title="How does the BTC&nbsp;Mixer work?">
                    </p>

                    <p>Here's how Whir works in three easy steps:</p>
                    <p>1) <strong>Enter the BTC address (or addresses) where you want to receive the mixed
                            BTC.</strong> Optionally, set the delay to process your transaction. The longer the
                        delay, the higher the anonymity of the mixed BTC.</p>
                    <p>2) <strong>Send the BTC you want to mix</strong> to the address generated by Whir.</p>
                    <p>3) <strong>After the first confirmation of your deposit, Whir will mix your BTC</strong>
                        and send them to the address (or addresses) entered in the first step.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-inner container-block promo-box bg-light lg-radius">
            <div class="boxes">
                <div class="box-sm-3">
                    <div class="sm-start center">
                        <img src="/assets/web/images/content-2-xs.png" width="280px" class="pixelated box-img"
                             alt="Isn’t BTC anonymous" title="Isn’t BTC anonymous">
                    </div>
                </div>

                <div class="box-sm-7">
                    <h2>But wait... isn’t BTC <u>anonymous</u>?</h2>
                    <div class="boxes">
                        <div class="box-sm-5">
                            <div class="pe-md-4">
                                <p>Absolutely not &mdash; BTC is pseudo-anonymous. <strong>Sending and receiving
                                        BTC leaves a fingerprint. </strong>If the fingerprint is ever linked to
                                    your
                                    identity, everything you have ever "touched" will be linked to you.</p></div>
                        </div>

                        <div class="box-sm-5">
                            <div class="pe-md-4">
                                <p>All the &ldquo;fingerprints&rdquo; are publicly stored in BTC&rsquo;s
                                    blockchain. Therefore, <strong>anyone you send BTC to can look up your
                                        previous transactions or even see your crypto balance.</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-inner container-block promo-box">
            <h2 class="center">
                How can a mixer make<br class="md-show"/> BTC anonymous?<br class="md-show"/> <u>CoinJoin</u> is
                the answer. </h2>

            <div class="boxes">
                <div class="box-md-2"></div>
                <div class="box-md-6">
                    <p><strong>CoinJoin is a type of anonymous transaction that helps BTC users maintain their
                            privacy while sending BTC.</strong> CoinJoin is a multiparty "BTC mixing"
                        transaction at the end of which it is unclear who owns which coin.</p>
                    <p>Consider the following transactions made at the same time: A purchases an item from B, C
                        purchases an item from D, and E purchases an item from F. Without CoinJoin, the public
                        blockchain ledger would record three separate transactions for each input-output match.</p>
                    <p>With CoinJoin, only one single transaction is recorded. The ledger would show that BTC
                        were paid from A, C, and E addresses to B, D, and F. By masking the deals made by all
                        parties, an observer cannot with full certainty determine who sent BTC to whom.</p>
                    <p>While some believe that CoinJoin is a new technology, this is not valid. CoinJoin is simply
                        an advancement on already existing technology &ndash; BTC. And BTC mixers bring
                        CoinJoin technology to users.</p>
                </div>
                <div class="box-md-2"></div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-inner container-block promo-box bg-light lg-radius">
            <div class="boxes">
                <div class="box-sm-3">
                    <div class="sm-start center">
                        <img src="/assets/web/images/content-3-xs.png" width="300px" class="pixelated box-img"
                             alt="Is it safe to use a BTC mixer?" title="Is it safe to use a BTC mixer?">
                    </div>
                </div>

                <div class="box-sm-7">
                    <h2>
                        <u>Is it safe</u> to use <br class="md-show"/>a BTC mixer? </h2>

                    <div class="boxes">
                        <div class="box-sm-5">
                            <div class="pe-md-4">
                                <p>It is absolutely safe to use Whir. However, as with almost everything else
                                    related to crypto, it is entirely up to you to decide whether it is necessary to
                                    use a BTC mixer.</p></div>
                        </div>

                        <div class="box-sm-5">
                            <div class="pe-md-4">
                                <p>Before using our Bitcon mixer, do a due diligence and read our <a
                                        href="{{url('/terms')}}">Terms</a>.<strong> However, we always suggest to
                                        mix
                                        smaller amounts instead of large chunks of coins at once.</strong></p></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="container-inner container-block promo-box">
            <h2 class="center">
                Why should I choose<br class="md-show"/> Whir BTC Mixer? </h2>

            <div class="boxes">
                <div class="box-md-2-5"></div>

                <div class="box-md-5">
                    <h3>FAST BTC MIXER</h3>
                    <p>The speed of a BTC mixer can be an important consideration for users who want to quickly
                        and efficiently obscure the origin of their BTC transactions.</p>
                    <p><strong>Whir BTC mixer offers an instant mixing service, which allows you to receive your
                            mixed BTC within a few minutes after the first confirmation of your
                            deposit. </strong>
                    </p>
                    <p>Optionally, to enhance the privacy of the BTC mixing transaction, you can choose a delay
                        in processing your mixing request.</p>
                    <h3>SECURE BTC MIXER</h3>
                    <p>The security of a BTC mixer can vary depending on the specific service being used. Some
                        BTC mixers may have strong security measures in place to protect the privacy of their
                        users, while others may be less secure.</p>
                    <p>It is important to carefully research any BTC mixer that you are considering using and to
                        ensure that they have strong security measures in place. This can include things like secure
                        servers, encrypted communication, and anonymous registration processes.</p>
                    <p>To guarantee the highest level of server and application security at all times, Whir employs
                        a team of IT and security specialists. <strong>Additionally, to increase the safety and
                            privacy of our users, we never require or log any personal details, such as name, email,
                            or IP address, and delete all transaction details after 24 hours. </strong></p>
                    <h3>CONVENIENT BTC MIXER</h3>
                    <p>The convenience of a BTC mixer can depend on a few factors, such as the user's specific
                        needs and the features and user experience of the mixer service being used.</p>
                    <p>Some users may find BTC mixers to be convenient because they allow them to quickly and
                        easily obscure the origin of their BTC transactions. Other users may find BTC mixers
                        to be inconvenient because they may have limits on the amount of BTC that can be mixed
                        at one time, or because they may require users to go through additional steps to use the
                        service.</p>
                    <p><strong>Whir BTC mixer combines the speed, privacy and affordability, while allowing you
                            to mix up to 10 BTC in a single transaction, without registration or KYC.</strong></p>
                </div>

                <div class="box-md-2-5"></div>
            </div>
        </div>
    </div>

    <div class="container container-md">
        <div class="container-inner container-block promo-box bg-light md-radius">
            <h2 class="center">BTC mixer FAQ</h2>
            {!! $faq !!}
            <p class="md-start center accordion-opts">
                <a class="btn btn-dark text-nouppercase" href="{{url('/faq')}}">
                    VIEW ALL FAQs </a>
            </p>
        </div>
    </div>

    <div class="container">
        <div class="container-inner container-block promo-box">
            <h2 class="md-center">
                Everyone has right<br class="md-show"/> for their <u>privacy</u>. </h2>

            <div class="boxes">
                <div class="box-md-1-5"></div>
                <div class="box-md-7  md-center">
                    <p><a href="#" target="_blank" rel="noopener"><strong>Privacy
                                is a fundamental human right</strong></a> recognized by the UN Declaration of Human
                        rights,
                        the International Covenant on Civil and Political Rights and in other treaties. No matter
                        who you are, Whir is for all of you*, and these are our clients:</p></div>
            </div>

            <div class="md-center faces">
                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-1-xs.png" alt="BTC mixer for activists"
                             title="BTC mixer for activists" height="115px">
                        <figcaption>Activists</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-2-xs.png" alt="BTC mixer for journalists"
                             title="BTC mixer for journalists" height="115px">
                        <figcaption>Journalists</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-3-xs.png" alt="BTC mixer for libertarians"
                             title="BTC mixer for libertarians" height="115px">
                        <figcaption>Libertarians</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-4-xs.png" alt="BTC mixer for sugar daddies"
                             title="BTC mixer for sugar daddies" height="115px">
                        <figcaption>Sugar daddies</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-6-xs.png" alt="BTC mixer for onlyfans"
                             title="BTC mixer for onlyfans" height="115px">
                        <figcaption>Onlyfans</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-5-xs.png" alt="BTC mixer for adults"
                             title="BTC mixer for adults" height="115px">
                        <figcaption>Adults</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-7-xs.png" alt="BTC mixer for privacy extremists"
                             title="BTC mixer for privacy extremists" height="115px">
                        <figcaption>Privacy extremists</figcaption>
                    </figure>
                </a>

                <a href="#">
                    <figure class="pixelated">
                        <img src="/assets/web/images/face-8-xs.png" alt="BTC mixer for cillionaires"
                             title="BTC mixer for cillionaires" height="115px">
                        <figcaption>Cillionaires</figcaption>
                    </figure>
                </a>
            </div>

            <div class="boxes">
                <div class="box-md-1-5"></div>
                <div class="box-md-7">
                    <div class="md-center privacy-appendix">
                        <p>* Okay, let&rsquo;s be clear. Privacy is absolutely vital for the bad guys, too. We,
                            however, do not support the crooks, and our service is not suitable for them either.
                            Even though Whir does the best to anonymize the transactions, there are far better coins
                            for crypto anonymity, such as <a href="#">Monero</a> or <a
                                href="#">zcash</a>. Please read <a href="{{url('terms')}}">our&nbsp;terms</a>
                            before use.</p></div>

                    <blockquote class="autoquote with-author">
                        People should have privacy. Governments should have transparency.
                    </blockquote>

                    <p class="center author">
                        — Julian Assange </p>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>
